version: '3.3'

services:
  loan_app_backend:
    container_name: loan_app_backend
    image: loan_app_backend
    build: ./backend
    # command: ""
    volumes:
      - "./backend:/app"
    ports:
      - "8000:8000"

  loan_app_frontend:
    container_name: loan_app_frontend
    image: loan_app_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - /frontend/node_modules
    environment:
      - BACKEND_URL=http://loan_app_backend/api/v1
    ports:
      - 3000:3000
    depends_on:
      - loan_app_backend